import {
  ArrowLeft,
  ArrowRight,
  BadgeDollarSign,
  BarChart3,
  Bell,
  Building2,
  Calendar,
  Check,
  CheckCircle,
  ClipboardList,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  Code2,
  Coins,
  Copy,
  CreditCard,
  DollarSign,
  Eye,
  Gauge,
  Gift,
  Globe,
  HelpCircle,
  Image,
  Info,
  Languages,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  LayoutTemplate,
  Link,
  Megaphone,
  MessageCircle,
  Monitor,
  MousePointerClick,
  Percent,
  Plus,
  PlusCircle,
  Presentation,
  Radar,
  RotateCcw,
  Search,
  Send,
  ShieldCheck,
  Sparkles,
  Square,
  Target,
  Type,
  Upload,
  Users,
  UsersRound,
  Wallet,
  X,
} from 'lucide-react'

// Only the icons the design actually uses — a static map keeps tree-shaking
// working (an `import * as` + dynamic lookup would bundle all of lucide).
const ICONS = {
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'badge-dollar-sign': BadgeDollarSign,
  'bar-chart-3': BarChart3,
  bell: Bell,
  'building-2': Building2,
  calendar: Calendar,
  check: Check,
  'check-circle': CheckCircle,
  'clipboard-list': ClipboardList,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'code-2': Code2,
  coins: Coins,
  copy: Copy,
  'credit-card': CreditCard,
  'dollar-sign': DollarSign,
  eye: Eye,
  gauge: Gauge,
  gift: Gift,
  globe: Globe,
  'help-circle': HelpCircle,
  image: Image,
  info: Info,
  languages: Languages,
  layers: Layers,
  'layout-dashboard': LayoutDashboard,
  'layout-grid': LayoutGrid,
  'layout-template': LayoutTemplate,
  link: Link,
  megaphone: Megaphone,
  'message-circle': MessageCircle,
  monitor: Monitor,
  'mouse-pointer-click': MousePointerClick,
  percent: Percent,
  plus: Plus,
  'plus-circle': PlusCircle,
  presentation: Presentation,
  radar: Radar,
  'rotate-ccw': RotateCcw,
  search: Search,
  send: Send,
  'shield-check': ShieldCheck,
  sparkles: Sparkles,
  target: Target,
  type: Type,
  upload: Upload,
  users: Users,
  'users-round': UsersRound,
  wallet: Wallet,
  x: X,
}

/**
 * Thin wrapper over lucide-react so we can keep the prototype's
 * `<i data-lucide="name">` idiom as `<Icon name="name" />`.
 *
 * The global `.lucide` rule (width/height: 1em, stroke-width, vertical-align)
 * sizes every icon to the surrounding font-size, exactly like the original.
 */
export default function Icon({ name, style, color, ...rest }) {
  const Cmp = ICONS[name] || Square
  return <Cmp className="lucide" color={color} style={style} {...rest} />
}
